inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - node_modules/**/*
    - db/schema.rb
require:
  - rubocop-sorbet
Sorbet:
  Enabled: true
Sorbet/ForbidSuperclassConstLiteral:
  Exclude:
    - db/migrate/*.rb
    - db/lhm/*.rb
